# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mtvcgui.ui'
#
# Created: Thu Nov 27 13:11:12 2008
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(190, 450, 95, 25))
        self.runButton.setObjectName("runButton")
        self.outputfile = QtGui.QLineEdit(self.centralwidget)
        self.outputfile.setGeometry(QtCore.QRect(115, 375, 571, 26))
        self.outputfile.setObjectName("outputfile")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 380, 101, 16))
        self.label.setObjectName("label")
        self.previewButton = QtGui.QPushButton(self.centralwidget)
        self.previewButton.setGeometry(QtCore.QRect(535, 410, 151, 25))
        self.previewButton.setObjectName("previewButton")
        self.previewcommand = QtGui.QLineEdit(self.centralwidget)
        self.previewcommand.setGeometry(QtCore.QRect(10, 410, 521, 26))
        self.previewcommand.setReadOnly(False)
        self.previewcommand.setObjectName("previewcommand")
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(380, 450, 95, 25))
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName("stopButton")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 681, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(50, 130, 66, 16))
        self.label_12.setObjectName("label_12")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 155, 54, 16))
        self.label_6.setObjectName("label_6")
        self.norm = QtGui.QSpinBox(self.tab)
        self.norm.setGeometry(QtCore.QRect(120, 150, 58, 26))
        self.norm.setProperty("value", QtCore.QVariant(0))
        self.norm.setObjectName("norm")
        self.driver = QtGui.QComboBox(self.tab)
        self.driver.setGeometry(QtCore.QRect(120, 90, 121, 26))
        self.driver.setEditable(True)
        self.driver.setObjectName("driver")
        self.driver.addItem(QtCore.QString())
        self.driver.addItem(QtCore.QString())
        self.device = QtGui.QLineEdit(self.tab)
        self.device.setGeometry(QtCore.QRect(120, 120, 121, 26))
        self.device.setObjectName("device")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(350, 30, 91, 16))
        self.label_8.setObjectName("label_8")
        self.videocodec = QtGui.QComboBox(self.tab)
        self.videocodec.setGeometry(QtCore.QRect(440, 65, 201, 26))
        self.videocodec.setEditable(True)
        self.videocodec.setObjectName("videocodec")
        self.videocodec.addItem(QtCore.QString())
        self.videocodec.addItem(QtCore.QString())
        self.videocodec.addItem(QtCore.QString())
        self.videocodec.addItem(QtCore.QString())
        self.videocodec.addItem(QtCore.QString())
        self.input = QtGui.QSpinBox(self.tab)
        self.input.setGeometry(QtCore.QRect(120, 180, 58, 26))
        self.input.setObjectName("input")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 54, 16))
        self.label_2.setObjectName("label_2")
        self.chanlist = QtGui.QComboBox(self.tab)
        self.chanlist.setGeometry(QtCore.QRect(120, 210, 121, 26))
        self.chanlist.setEditable(True)
        self.chanlist.setObjectName("chanlist")
        self.chanlist.addItem(QtCore.QString())
        self.chanlist.addItem(QtCore.QString())
        self.chanlist.addItem(QtCore.QString())
        self.chanlist.addItem(QtCore.QString())
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(50, 215, 54, 16))
        self.label_7.setObjectName("label_7")
        self.channel = QtGui.QSpinBox(self.tab)
        self.channel.setGeometry(QtCore.QRect(120, 30, 58, 26))
        self.channel.setObjectName("channel")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 71, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(50, 70, 66, 16))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(350, 70, 91, 16))
        self.label_9.setObjectName("label_9")
        self.audiocodec = QtGui.QComboBox(self.tab)
        self.audiocodec.setGeometry(QtCore.QRect(440, 25, 201, 26))
        self.audiocodec.setEditable(True)
        self.audiocodec.setObjectName("audiocodec")
        self.audiocodec.addItem(QtCore.QString())
        self.audiocodec.addItem(QtCore.QString())
        self.audiocodec.addItem(QtCore.QString())
        self.audiocodec.addItem(QtCore.QString())
        self.audiocodec.addItem(QtCore.QString())
        self.duration = QtGui.QTimeEdit(self.tab)
        self.duration.setGeometry(QtCore.QRect(120, 60, 118, 26))
        self.duration.setObjectName("duration")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(50, 185, 61, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(320, 105, 341, 181))
        self.groupBox.setObjectName("groupBox")
        self.lavc_audiocodec = QtGui.QLineEdit(self.groupBox)
        self.lavc_audiocodec.setGeometry(QtCore.QRect(160, 30, 113, 26))
        self.lavc_audiocodec.setObjectName("lavc_audiocodec")
        self.lavc_audiobitrate = QtGui.QLineEdit(self.groupBox)
        self.lavc_audiobitrate.setGeometry(QtCore.QRect(160, 60, 113, 26))
        self.lavc_audiobitrate.setObjectName("lavc_audiobitrate")
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label_20.setObjectName("label_20")
        self.lavc_videocodec = QtGui.QLineEdit(self.groupBox)
        self.lavc_videocodec.setGeometry(QtCore.QRect(160, 90, 113, 26))
        self.lavc_videocodec.setObjectName("lavc_videocodec")
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(20, 95, 81, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(20, 125, 81, 16))
        self.label_22.setObjectName("label_22")
        self.lavc_videobitrate = QtGui.QLineEdit(self.groupBox)
        self.lavc_videobitrate.setGeometry(QtCore.QRect(160, 120, 113, 26))
        self.lavc_videobitrate.setObjectName("lavc_videobitrate")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(40, 210, 231, 16))
        self.label_10.setObjectName("label_10")
        self.extratvparms = QtGui.QLineEdit(self.tab_2)
        self.extratvparms.setGeometry(QtCore.QRect(32, 230, 541, 26))
        self.extratvparms.setObjectName("extratvparms")
        self.tvwidth = QtGui.QLineEdit(self.tab_2)
        self.tvwidth.setGeometry(QtCore.QRect(110, 10, 113, 26))
        self.tvwidth.setObjectName("tvwidth")
        self.tvheight = QtGui.QLineEdit(self.tab_2)
        self.tvheight.setGeometry(QtCore.QRect(110, 40, 113, 26))
        self.tvheight.setObjectName("tvheight")
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 45, 96, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_14.setObjectName("label_14")
        self.audiorate = QtGui.QLineEdit(self.tab_2)
        self.audiorate.setGeometry(QtCore.QRect(110, 70, 113, 26))
        self.audiorate.setObjectName("audiorate")
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 75, 81, 46))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 220, 451, 16))
        self.label_11.setObjectName("label_11")
        self.extramencoderparms = QtGui.QLineEdit(self.tab_3)
        self.extramencoderparms.setGeometry(QtCore.QRect(32, 240, 541, 26))
        self.extramencoderparms.setObjectName("extramencoderparms")
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 66, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 45, 61, 16))
        self.label_16.setObjectName("label_16")
        self.scalewidth = QtGui.QLineEdit(self.tab_3)
        self.scalewidth.setGeometry(QtCore.QRect(90, 10, 113, 26))
        self.scalewidth.setObjectName("scalewidth")
        self.scaleheight = QtGui.QLineEdit(self.tab_3)
        self.scaleheight.setGeometry(QtCore.QRect(90, 40, 113, 26))
        self.scaleheight.setObjectName("scaleheight")
        self.noskip = QtGui.QCheckBox(self.tab_3)
        self.noskip.setGeometry(QtCore.QRect(420, 20, 84, 23))
        self.noskip.setObjectName("noskip")
        self.quiet = QtGui.QCheckBox(self.tab_3)
        self.quiet.setGeometry(QtCore.QRect(420, 50, 84, 23))
        self.quiet.setChecked(True)
        self.quiet.setObjectName("quiet")
        self.ofps = QtGui.QLineEdit(self.tab_3)
        self.ofps.setGeometry(QtCore.QRect(90, 70, 113, 26))
        self.ofps.setObjectName("ofps")
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(20, 75, 61, 16))
        self.label_18.setObjectName("label_18")
        self.extrafilters = QtGui.QLineEdit(self.tab_3)
        self.extrafilters.setGeometry(QtCore.QRect(30, 180, 541, 26))
        self.extrafilters.setObjectName("extrafilters")
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(40, 160, 456, 16))
        self.label_23.setObjectName("label_23")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 24))
        self.menubar.setObjectName("menubar")
        self.menuPrueba = QtGui.QMenu(self.menubar)
        self.menuPrueba.setObjectName("menuPrueba")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionSave_configuration = QtGui.QAction(MainWindow)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionAbout_mtvcgui = QtGui.QAction(MainWindow)
        self.actionAbout_mtvcgui.setObjectName("actionAbout_mtvcgui")
        self.menuPrueba.addAction(self.actionSave_configuration)
        self.menuPrueba.addAction(self.actionSalir)
        self.menuHelp.addAction(self.actionAbout_mtvcgui)
        self.menubar.addAction(self.menuPrueba.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.runButton, QtCore.SIGNAL("clicked()"), MainWindow.runMencoder)
        QtCore.QObject.connect(self.previewButton, QtCore.SIGNAL("clicked()"), MainWindow.previewCommand)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL("clicked()"), MainWindow.stopButtonPressed)
        QtCore.QObject.connect(self.actionSave_configuration, QtCore.SIGNAL("activated()"), MainWindow.saveConfiguration)
        QtCore.QObject.connect(self.actionAbout_mtvcgui, QtCore.SIGNAL("activated()"), MainWindow.showAboutDialog)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mencoder TV Capture GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.outputfile.setText(QtGui.QApplication.translate("MainWindow", "./mencoder_tv_capture.avi", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("MainWindow", "preview command", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "norm[id]", None, QtGui.QApplication.UnicodeUTF8))
        self.norm.setToolTip(QtGui.QApplication.translate("MainWindow", "0 = NTSC\n"
"1 = NTSC-M\n"
"2 = NTSC-M-JP\n"
"3 = NTSC-M-KR\n"
"4 = PAL\n"
"5 = PAL-BG\n"
"6 = PAL-H\n"
"7 = PAL-I\n"
"8 = PAL-DK\n"
"9 = PAL-M\n"
"10 = PAL-N\n"
"11 = PAL-Nc\n"
"12 = PAL-60\n"
"13 = SECAM\n"
"14 = SECAM-B\n"
"15 = SECAM-G\n"
"16 = SECAM-H\n"
"17 = SECAM-DK\n"
"18 = SECAM-L\n"
"19 = SECAM-Lc", None, QtGui.QApplication.UnicodeUTF8))
        self.driver.setItemText(0, QtGui.QApplication.translate("MainWindow", "v4l2", None, QtGui.QApplication.UnicodeUTF8))
        self.driver.setItemText(1, QtGui.QApplication.translate("MainWindow", "v4l", None, QtGui.QApplication.UnicodeUTF8))
        self.device.setText(QtGui.QApplication.translate("MainWindow", "/dev/video0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(1, QtGui.QApplication.translate("MainWindow", "raw", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(2, QtGui.QApplication.translate("MainWindow", "lavc", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(3, QtGui.QApplication.translate("MainWindow", "libdv", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(4, QtGui.QApplication.translate("MainWindow", "xvid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(0, QtGui.QApplication.translate("MainWindow", "us-cable", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(1, QtGui.QApplication.translate("MainWindow", "us-bcast", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(2, QtGui.QApplication.translate("MainWindow", "europe-east", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(3, QtGui.QApplication.translate("MainWindow", "europe-west", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "chanlist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(1, QtGui.QApplication.translate("MainWindow", "copy", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(2, QtGui.QApplication.translate("MainWindow", "pcm", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(3, QtGui.QApplication.translate("MainWindow", "mp3lame", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(4, QtGui.QApplication.translate("MainWindow", "lavc", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "lavc options", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiocodec.setText(QtGui.QApplication.translate("MainWindow", "mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiobitrate.setText(QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Audio Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setText(QtGui.QApplication.translate("MainWindow", "mpeg4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Video Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videobitrate.setText(QtGui.QApplication.translate("MainWindow", "3000", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Main Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Extra tv parameters (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Audio Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Extra TV Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Extra mencoder parameters (delimited by spaces)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.noskip.setText(QtGui.QApplication.translate("MainWindow", "noskip", None, QtGui.QApplication.UnicodeUTF8))
        self.quiet.setText(QtGui.QApplication.translate("MainWindow", "quiet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "FPS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Extra filters (delimited by ,)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Extra Mencoder Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPrueba.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_configuration.setText(QtGui.QApplication.translate("MainWindow", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_mtvcgui.setText(QtGui.QApplication.translate("MainWindow", "About mtvcgui", None, QtGui.QApplication.UnicodeUTF8))

