# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mtvcgui.ui'
#
# Created: Thu Jun 21 21:24:45 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(694, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(190, 450, 95, 25))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.outputfile = QtGui.QLineEdit(self.centralwidget)
        self.outputfile.setGeometry(QtCore.QRect(125, 360, 561, 26))
        self.outputfile.setText(_fromUtf8("./capture_{%channel_%Y%m%d_%H%M%S}.avi"))
        self.outputfile.setObjectName(_fromUtf8("outputfile"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 365, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.previewButton = QtGui.QPushButton(self.centralwidget)
        self.previewButton.setGeometry(QtCore.QRect(505, 415, 186, 26))
        self.previewButton.setObjectName(_fromUtf8("previewButton"))
        self.previewcommand = QtGui.QLineEdit(self.centralwidget)
        self.previewcommand.setGeometry(QtCore.QRect(0, 415, 506, 26))
        self.previewcommand.setText(_fromUtf8(""))
        self.previewcommand.setReadOnly(False)
        self.previewcommand.setObjectName(_fromUtf8("previewcommand"))
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(380, 450, 95, 25))
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 681, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 131, 91, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 161, 96, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.driver = QtGui.QComboBox(self.tab)
        self.driver.setGeometry(QtCore.QRect(110, 95, 121, 26))
        self.driver.setEditable(True)
        self.driver.setObjectName(_fromUtf8("driver"))
        self.driver.addItem(_fromUtf8(""))
        self.driver.setItemText(0, _fromUtf8("v4l2"))
        self.driver.addItem(_fromUtf8(""))
        self.driver.setItemText(1, _fromUtf8("v4l"))
        self.device = QtGui.QLineEdit(self.tab)
        self.device.setGeometry(QtCore.QRect(110, 125, 121, 26))
        self.device.setText(_fromUtf8("/dev/video0"))
        self.device.setObjectName(_fromUtf8("device"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(320, 20, 111, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.videocodec = QtGui.QComboBox(self.tab)
        self.videocodec.setGeometry(QtCore.QRect(440, 45, 201, 26))
        self.videocodec.setEditable(True)
        self.videocodec.setObjectName(_fromUtf8("videocodec"))
        self.videocodec.addItem(_fromUtf8(""))
        self.videocodec.setItemText(0, _fromUtf8("null"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 41, 96, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.chanlist = QtGui.QComboBox(self.tab)
        self.chanlist.setGeometry(QtCore.QRect(110, 215, 121, 26))
        self.chanlist.setEditable(True)
        self.chanlist.setObjectName(_fromUtf8("chanlist"))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.setItemText(0, _fromUtf8("us-cable"))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.setItemText(1, _fromUtf8("us-bcast"))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.setItemText(2, _fromUtf8("europe-east"))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.setItemText(3, _fromUtf8("europe-west"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 221, 96, 31))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.channel = QtGui.QSpinBox(self.tab)
        self.channel.setGeometry(QtCore.QRect(110, 35, 58, 26))
        self.channel.setObjectName(_fromUtf8("channel"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 101, 96, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 71, 96, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(320, 50, 111, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.audiocodec = QtGui.QComboBox(self.tab)
        self.audiocodec.setGeometry(QtCore.QRect(440, 15, 201, 26))
        self.audiocodec.setEditable(True)
        self.audiocodec.setObjectName(_fromUtf8("audiocodec"))
        self.audiocodec.addItem(_fromUtf8(""))
        self.audiocodec.setItemText(0, _fromUtf8("null"))
        self.duration = QtGui.QTimeEdit(self.tab)
        self.duration.setGeometry(QtCore.QRect(110, 65, 121, 26))
        self.duration.setObjectName(_fromUtf8("duration"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 191, 96, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lavc_audio_options_box = QtGui.QGroupBox(self.tab)
        self.lavc_audio_options_box.setGeometry(QtCore.QRect(310, 80, 361, 111))
        self.lavc_audio_options_box.setObjectName(_fromUtf8("lavc_audio_options_box"))
        self.lavc_audiobitrate = QtGui.QLineEdit(self.lavc_audio_options_box)
        self.lavc_audiobitrate.setGeometry(QtCore.QRect(235, 55, 113, 26))
        self.lavc_audiobitrate.setText(_fromUtf8("128"))
        self.lavc_audiobitrate.setObjectName(_fromUtf8("lavc_audiobitrate"))
        self.label_19 = QtGui.QLabel(self.lavc_audio_options_box)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 216, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.lavc_audio_options_box)
        self.label_20.setGeometry(QtCore.QRect(10, 60, 216, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lavc_audiocodec = QtGui.QComboBox(self.lavc_audio_options_box)
        self.lavc_audiocodec.setGeometry(QtCore.QRect(235, 25, 111, 26))
        self.lavc_audiocodec.setEditable(True)
        self.lavc_audiocodec.setObjectName(_fromUtf8("lavc_audiocodec"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(0, _fromUtf8("mp2"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(1, _fromUtf8("libmp3lame"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(2, _fromUtf8("ac3"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(3, _fromUtf8("flac"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(4, _fromUtf8("vorbis"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.setItemText(5, _fromUtf8("adpcm_ima_wav"))
        self.lavc_audio_extra_opts = QtGui.QLineEdit(self.lavc_audio_options_box)
        self.lavc_audio_extra_opts.setGeometry(QtCore.QRect(235, 85, 113, 26))
        self.lavc_audio_extra_opts.setText(_fromUtf8(""))
        self.lavc_audio_extra_opts.setObjectName(_fromUtf8("lavc_audio_extra_opts"))
        self.label_40 = QtGui.QLabel(self.lavc_audio_options_box)
        self.label_40.setGeometry(QtCore.QRect(10, 90, 216, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.showAudioCodecsButton = QtGui.QToolButton(self.tab)
        self.showAudioCodecsButton.setGeometry(QtCore.QRect(645, 15, 27, 25))
        self.showAudioCodecsButton.setText(_fromUtf8("..."))
        self.showAudioCodecsButton.setObjectName(_fromUtf8("showAudioCodecsButton"))
        self.showVideoCodecsButton = QtGui.QToolButton(self.tab)
        self.showVideoCodecsButton.setGeometry(QtCore.QRect(645, 45, 27, 25))
        self.showVideoCodecsButton.setText(_fromUtf8("..."))
        self.showVideoCodecsButton.setObjectName(_fromUtf8("showVideoCodecsButton"))
        self.number_rb = QtGui.QRadioButton(self.tab)
        self.number_rb.setGeometry(QtCore.QRect(235, 15, 96, 25))
        self.number_rb.setChecked(True)
        self.number_rb.setObjectName(_fromUtf8("number_rb"))
        self.freq_rb = QtGui.QRadioButton(self.tab)
        self.freq_rb.setGeometry(QtCore.QRect(235, 40, 96, 25))
        self.freq_rb.setObjectName(_fromUtf8("freq_rb"))
        self.frequency = QtGui.QDoubleSpinBox(self.tab)
        self.frequency.setGeometry(QtCore.QRect(111, 35, 121, 26))
        self.frequency.setDecimals(3)
        self.frequency.setMaximum(9999.99)
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 260, 221, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lavc_video_options_box = QtGui.QGroupBox(self.tab)
        self.lavc_video_options_box.setGeometry(QtCore.QRect(310, 195, 361, 121))
        self.lavc_video_options_box.setObjectName(_fromUtf8("lavc_video_options_box"))
        self.label_22 = QtGui.QLabel(self.lavc_video_options_box)
        self.label_22.setGeometry(QtCore.QRect(15, 60, 136, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_21 = QtGui.QLabel(self.lavc_video_options_box)
        self.label_21.setGeometry(QtCore.QRect(15, 30, 136, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lavc_videobitrate = QtGui.QLineEdit(self.lavc_video_options_box)
        self.lavc_videobitrate.setGeometry(QtCore.QRect(220, 55, 131, 26))
        self.lavc_videobitrate.setText(_fromUtf8("3000"))
        self.lavc_videobitrate.setObjectName(_fromUtf8("lavc_videobitrate"))
        self.lavc_videocodec = QtGui.QComboBox(self.lavc_video_options_box)
        self.lavc_videocodec.setGeometry(QtCore.QRect(220, 25, 131, 26))
        self.lavc_videocodec.setEditable(True)
        self.lavc_videocodec.setObjectName(_fromUtf8("lavc_videocodec"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(0, _fromUtf8("mpeg4"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(1, _fromUtf8("mjpeg"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(2, _fromUtf8("h263"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(3, _fromUtf8("h263p"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(4, _fromUtf8("mspeg4"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(5, _fromUtf8("mspeg4v2"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(6, _fromUtf8("wmv1"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(7, _fromUtf8("wmv2"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(8, _fromUtf8("rv10"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(9, _fromUtf8("rv20"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(10, _fromUtf8("mpeg1video"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(11, _fromUtf8("huffyuv"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.setItemText(12, _fromUtf8("flv"))
        self.label_41 = QtGui.QLabel(self.lavc_video_options_box)
        self.label_41.setGeometry(QtCore.QRect(15, 90, 201, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.lavc_video_extra_opts = QtGui.QLineEdit(self.lavc_video_options_box)
        self.lavc_video_extra_opts.setGeometry(QtCore.QRect(220, 85, 131, 26))
        self.lavc_video_extra_opts.setText(_fromUtf8(""))
        self.lavc_video_extra_opts.setObjectName(_fromUtf8("lavc_video_extra_opts"))
        self.lame_options_box = QtGui.QGroupBox(self.tab)
        self.lame_options_box.setGeometry(QtCore.QRect(310, 80, 361, 101))
        self.lame_options_box.setObjectName(_fromUtf8("lame_options_box"))
        self.label_28 = QtGui.QLabel(self.lame_options_box)
        self.label_28.setGeometry(QtCore.QRect(10, 30, 206, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lame_audiobitrate = QtGui.QLineEdit(self.lame_options_box)
        self.lame_audiobitrate.setGeometry(QtCore.QRect(230, 25, 113, 26))
        self.lame_audiobitrate.setText(_fromUtf8("128"))
        self.lame_audiobitrate.setObjectName(_fromUtf8("lame_audiobitrate"))
        self.extra_lame_opts_label = QtGui.QLabel(self.lame_options_box)
        self.extra_lame_opts_label.setGeometry(QtCore.QRect(10, 65, 216, 16))
        self.extra_lame_opts_label.setObjectName(_fromUtf8("extra_lame_opts_label"))
        self.lame_extra_opts = QtGui.QLineEdit(self.lame_options_box)
        self.lame_extra_opts.setGeometry(QtCore.QRect(230, 60, 113, 26))
        self.lame_extra_opts.setText(_fromUtf8(""))
        self.lame_extra_opts.setObjectName(_fromUtf8("lame_extra_opts"))
        self.norm = QtGui.QComboBox(self.tab)
        self.norm.setGeometry(QtCore.QRect(110, 155, 121, 26))
        self.norm.setEditable(True)
        self.norm.setObjectName(_fromUtf8("norm"))
        self.input = QtGui.QComboBox(self.tab)
        self.input.setGeometry(QtCore.QRect(110, 185, 121, 26))
        self.input.setEditable(True)
        self.input.setObjectName(_fromUtf8("input"))
        self.x264_options_box = QtGui.QGroupBox(self.tab)
        self.x264_options_box.setGeometry(QtCore.QRect(310, 195, 361, 96))
        self.x264_options_box.setObjectName(_fromUtf8("x264_options_box"))
        self.x264_bitrate = QtGui.QLineEdit(self.x264_options_box)
        self.x264_bitrate.setGeometry(QtCore.QRect(105, 25, 113, 21))
        self.x264_bitrate.setText(_fromUtf8(""))
        self.x264_bitrate.setObjectName(_fromUtf8("x264_bitrate"))
        self.x264_bitrate_label = QtGui.QLabel(self.x264_options_box)
        self.x264_bitrate_label.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.x264_bitrate_label.setObjectName(_fromUtf8("x264_bitrate_label"))
        self.x264_qp_label = QtGui.QLabel(self.x264_options_box)
        self.x264_qp_label.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.x264_qp_label.setObjectName(_fromUtf8("x264_qp_label"))
        self.x264_qp = QtGui.QLineEdit(self.x264_options_box)
        self.x264_qp.setGeometry(QtCore.QRect(105, 25, 113, 21))
        self.x264_qp.setText(_fromUtf8(""))
        self.x264_qp.setObjectName(_fromUtf8("x264_qp"))
        self.label_39 = QtGui.QLabel(self.x264_options_box)
        self.label_39.setGeometry(QtCore.QRect(10, 75, 201, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.x264_extra_opts = QtGui.QLineEdit(self.x264_options_box)
        self.x264_extra_opts.setGeometry(QtCore.QRect(215, 70, 141, 21))
        self.x264_extra_opts.setToolTip(_fromUtf8(""))
        self.x264_extra_opts.setText(_fromUtf8(""))
        self.x264_extra_opts.setObjectName(_fromUtf8("x264_extra_opts"))
        self.x264_cbr = QtGui.QCheckBox(self.x264_options_box)
        self.x264_cbr.setGeometry(QtCore.QRect(230, 25, 80, 21))
        self.x264_cbr.setObjectName(_fromUtf8("x264_cbr"))
        self.x264_crf = QtGui.QLineEdit(self.x264_options_box)
        self.x264_crf.setGeometry(QtCore.QRect(105, 50, 111, 21))
        self.x264_crf.setObjectName(_fromUtf8("x264_crf"))
        self.x264_crf_label = QtGui.QLabel(self.x264_options_box)
        self.x264_crf_label.setGeometry(QtCore.QRect(10, 55, 52, 13))
        self.x264_crf_label.setObjectName(_fromUtf8("x264_crf_label"))
        self.xvid_options_box = QtGui.QGroupBox(self.tab)
        self.xvid_options_box.setGeometry(QtCore.QRect(310, 195, 361, 121))
        self.xvid_options_box.setObjectName(_fromUtf8("xvid_options_box"))
        self.xvid_bitrate_label = QtGui.QLabel(self.xvid_options_box)
        self.xvid_bitrate_label.setGeometry(QtCore.QRect(5, 25, 91, 16))
        self.xvid_bitrate_label.setObjectName(_fromUtf8("xvid_bitrate_label"))
        self.xvid_fixed_quant_label = QtGui.QLabel(self.xvid_options_box)
        self.xvid_fixed_quant_label.setGeometry(QtCore.QRect(5, 25, 91, 16))
        self.xvid_fixed_quant_label.setObjectName(_fromUtf8("xvid_fixed_quant_label"))
        self.label_35 = QtGui.QLabel(self.xvid_options_box)
        self.label_35.setGeometry(QtCore.QRect(5, 55, 91, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.xvid_bitrate = QtGui.QLineEdit(self.xvid_options_box)
        self.xvid_bitrate.setGeometry(QtCore.QRect(97, 20, 96, 21))
        self.xvid_bitrate.setText(_fromUtf8(""))
        self.xvid_bitrate.setObjectName(_fromUtf8("xvid_bitrate"))
        self.xvid_fixed_quant = QtGui.QLineEdit(self.xvid_options_box)
        self.xvid_fixed_quant.setGeometry(QtCore.QRect(97, 20, 96, 21))
        self.xvid_fixed_quant.setText(_fromUtf8(""))
        self.xvid_fixed_quant.setObjectName(_fromUtf8("xvid_fixed_quant"))
        self.xvid_me_quality = QtGui.QLineEdit(self.xvid_options_box)
        self.xvid_me_quality.setGeometry(QtCore.QRect(97, 50, 96, 21))
        self.xvid_me_quality.setText(_fromUtf8(""))
        self.xvid_me_quality.setObjectName(_fromUtf8("xvid_me_quality"))
        self.xvid_interlacing = QtGui.QCheckBox(self.xvid_options_box)
        self.xvid_interlacing.setGeometry(QtCore.QRect(210, 45, 141, 21))
        self.xvid_interlacing.setObjectName(_fromUtf8("xvid_interlacing"))
        self.xvid_cartoon = QtGui.QCheckBox(self.xvid_options_box)
        self.xvid_cartoon.setGeometry(QtCore.QRect(210, 70, 141, 21))
        self.xvid_cartoon.setObjectName(_fromUtf8("xvid_cartoon"))
        self.label_36 = QtGui.QLabel(self.xvid_options_box)
        self.label_36.setGeometry(QtCore.QRect(5, 100, 206, 16))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.xvid_extra_opts = QtGui.QLineEdit(self.xvid_options_box)
        self.xvid_extra_opts.setGeometry(QtCore.QRect(210, 95, 146, 21))
        self.xvid_extra_opts.setText(_fromUtf8(""))
        self.xvid_extra_opts.setObjectName(_fromUtf8("xvid_extra_opts"))
        self.xvid_cbr = QtGui.QCheckBox(self.xvid_options_box)
        self.xvid_cbr.setGeometry(QtCore.QRect(210, 20, 136, 21))
        self.xvid_cbr.setObjectName(_fromUtf8("xvid_cbr"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(15, 210, 521, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.extratvparms = QtGui.QLineEdit(self.tab_2)
        self.extratvparms.setGeometry(QtCore.QRect(10, 230, 636, 26))
        self.extratvparms.setText(_fromUtf8(""))
        self.extratvparms.setObjectName(_fromUtf8("extratvparms"))
        self.tvwidth = QtGui.QLineEdit(self.tab_2)
        self.tvwidth.setGeometry(QtCore.QRect(110, 10, 113, 26))
        self.tvwidth.setText(_fromUtf8(""))
        self.tvwidth.setObjectName(_fromUtf8("tvwidth"))
        self.tvheight = QtGui.QLineEdit(self.tab_2)
        self.tvheight.setGeometry(QtCore.QRect(110, 40, 113, 26))
        self.tvheight.setText(_fromUtf8(""))
        self.tvheight.setObjectName(_fromUtf8("tvheight"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 45, 96, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.audiorate = QtGui.QLineEdit(self.tab_2)
        self.audiorate.setGeometry(QtCore.QRect(110, 70, 113, 26))
        self.audiorate.setText(_fromUtf8(""))
        self.audiorate.setObjectName(_fromUtf8("audiorate"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 75, 81, 46))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(230, 75, 54, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.alsa_audio = QtGui.QCheckBox(self.tab_2)
        self.alsa_audio.setGeometry(QtCore.QRect(10, 125, 321, 23))
        self.alsa_audio.setObjectName(_fromUtf8("alsa_audio"))
        self.adevice = QtGui.QLineEdit(self.tab_2)
        self.adevice.setGeometry(QtCore.QRect(10, 155, 131, 26))
        self.adevice.setText(_fromUtf8(""))
        self.adevice.setObjectName(_fromUtf8("adevice"))
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(150, 160, 216, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.brightnessSlider = QtGui.QSlider(self.tab_2)
        self.brightnessSlider.setGeometry(QtCore.QRect(490, 15, 160, 23))
        self.brightnessSlider.setMinimum(-100)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.brightnessSlider.setObjectName(_fromUtf8("brightnessSlider"))
        self.contrastSlider = QtGui.QSlider(self.tab_2)
        self.contrastSlider.setGeometry(QtCore.QRect(490, 45, 160, 23))
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.contrastSlider.setObjectName(_fromUtf8("contrastSlider"))
        self.hueSlider = QtGui.QSlider(self.tab_2)
        self.hueSlider.setGeometry(QtCore.QRect(490, 75, 160, 23))
        self.hueSlider.setMinimum(-100)
        self.hueSlider.setMaximum(100)
        self.hueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hueSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.hueSlider.setObjectName(_fromUtf8("hueSlider"))
        self.saturationSlider = QtGui.QSlider(self.tab_2)
        self.saturationSlider.setGeometry(QtCore.QRect(490, 105, 160, 23))
        self.saturationSlider.setMinimum(-100)
        self.saturationSlider.setMaximum(100)
        self.saturationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturationSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.saturationSlider.setObjectName(_fromUtf8("saturationSlider"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(385, 15, 86, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(385, 45, 101, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(385, 75, 101, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(385, 105, 101, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 220, 451, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.extramencoderparms = QtGui.QLineEdit(self.tab_3)
        self.extramencoderparms.setGeometry(QtCore.QRect(20, 240, 540, 26))
        self.extramencoderparms.setText(_fromUtf8(""))
        self.extramencoderparms.setObjectName(_fromUtf8("extramencoderparms"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 66, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 45, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.scalewidth = QtGui.QLineEdit(self.tab_3)
        self.scalewidth.setGeometry(QtCore.QRect(90, 10, 113, 26))
        self.scalewidth.setText(_fromUtf8(""))
        self.scalewidth.setObjectName(_fromUtf8("scalewidth"))
        self.scaleheight = QtGui.QLineEdit(self.tab_3)
        self.scaleheight.setGeometry(QtCore.QRect(90, 40, 113, 26))
        self.scaleheight.setText(_fromUtf8(""))
        self.scaleheight.setObjectName(_fromUtf8("scaleheight"))
        self.noskip = QtGui.QCheckBox(self.tab_3)
        self.noskip.setGeometry(QtCore.QRect(420, 20, 156, 23))
        self.noskip.setObjectName(_fromUtf8("noskip"))
        self.quiet = QtGui.QCheckBox(self.tab_3)
        self.quiet.setGeometry(QtCore.QRect(420, 50, 151, 23))
        self.quiet.setChecked(True)
        self.quiet.setObjectName(_fromUtf8("quiet"))
        self.ofps = QtGui.QLineEdit(self.tab_3)
        self.ofps.setGeometry(QtCore.QRect(90, 70, 113, 26))
        self.ofps.setText(_fromUtf8(""))
        self.ofps.setObjectName(_fromUtf8("ofps"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(20, 75, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.extrafilters = QtGui.QLineEdit(self.tab_3)
        self.extrafilters.setGeometry(QtCore.QRect(20, 180, 540, 26))
        self.extrafilters.setText(_fromUtf8(""))
        self.extrafilters.setObjectName(_fromUtf8("extrafilters"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(20, 160, 456, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(20, 15, 621, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(20, 85, 616, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.pre_command = QtGui.QLineEdit(self.tab_4)
        self.pre_command.setGeometry(QtCore.QRect(15, 30, 626, 26))
        self.pre_command.setText(_fromUtf8(""))
        self.pre_command.setObjectName(_fromUtf8("pre_command"))
        self.post_command = QtGui.QLineEdit(self.tab_4)
        self.post_command.setGeometry(QtCore.QRect(15, 105, 626, 26))
        self.post_command.setText(_fromUtf8(""))
        self.post_command.setObjectName(_fromUtf8("post_command"))
        self.recording_date = QtGui.QDateTimeEdit(self.tab_4)
        self.recording_date.setGeometry(QtCore.QRect(15, 270, 194, 26))
        self.recording_date.setObjectName(_fromUtf8("recording_date"))
        self.scheduleButton = QtGui.QPushButton(self.tab_4)
        self.scheduleButton.setGeometry(QtCore.QRect(230, 270, 186, 25))
        self.scheduleButton.setObjectName(_fromUtf8("scheduleButton"))
        self.cancel_sheduleButton = QtGui.QPushButton(self.tab_4)
        self.cancel_sheduleButton.setEnabled(False)
        self.cancel_sheduleButton.setGeometry(QtCore.QRect(440, 270, 186, 25))
        self.cancel_sheduleButton.setCheckable(False)
        self.cancel_sheduleButton.setObjectName(_fromUtf8("cancel_sheduleButton"))
        self.play_while_recording = QtGui.QCheckBox(self.tab_4)
        self.play_while_recording.setGeometry(QtCore.QRect(15, 130, 636, 46))
        self.play_while_recording.setObjectName(_fromUtf8("play_while_recording"))
        self.setenvvars = QtGui.QCheckBox(self.tab_4)
        self.setenvvars.setGeometry(QtCore.QRect(15, 175, 611, 21))
        self.setenvvars.setChecked(True)
        self.setenvvars.setObjectName(_fromUtf8("setenvvars"))
        self.envvars = QtGui.QPlainTextEdit(self.tab_4)
        self.envvars.setGeometry(QtCore.QRect(15, 200, 626, 66))
        self.envvars.setPlainText(_fromUtf8("LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so"))
        self.envvars.setObjectName(_fromUtf8("envvars"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.append_suffix = QtGui.QCheckBox(self.centralwidget)
        self.append_suffix.setGeometry(QtCore.QRect(10, 385, 666, 23))
        self.append_suffix.setChecked(True)
        self.append_suffix.setObjectName(_fromUtf8("append_suffix"))
        self.status_label = QtGui.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(495, 455, 186, 16))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPrueba = QtGui.QMenu(self.menubar)
        self.menuPrueba.setObjectName(_fromUtf8("menuPrueba"))
        self.menuChange_language = QtGui.QMenu(self.menuPrueba)
        self.menuChange_language.setObjectName(_fromUtf8("menuChange_language"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionSave_configuration = QtGui.QAction(MainWindow)
        self.actionSave_configuration.setObjectName(_fromUtf8("actionSave_configuration"))
        self.actionAbout_mtvcgui = QtGui.QAction(MainWindow)
        self.actionAbout_mtvcgui.setObjectName(_fromUtf8("actionAbout_mtvcgui"))
        self.actionReload_configuration = QtGui.QAction(MainWindow)
        self.actionReload_configuration.setObjectName(_fromUtf8("actionReload_configuration"))
        self.actionEnglish = QtGui.QAction(MainWindow)
        self.actionEnglish.setObjectName(_fromUtf8("actionEnglish"))
        self.actionSpanish = QtGui.QAction(MainWindow)
        self.actionSpanish.setObjectName(_fromUtf8("actionSpanish"))
        self.actionSpanish_Argentina = QtGui.QAction(MainWindow)
        self.actionSpanish_Argentina.setObjectName(_fromUtf8("actionSpanish_Argentina"))
        self.actionItalian = QtGui.QAction(MainWindow)
        self.actionItalian.setObjectName(_fromUtf8("actionItalian"))
        self.menuChange_language.addAction(self.actionEnglish)
        self.menuChange_language.addAction(self.actionSpanish)
        self.menuChange_language.addAction(self.actionSpanish_Argentina)
        self.menuChange_language.addAction(self.actionItalian)
        self.menuPrueba.addAction(self.actionSave_configuration)
        self.menuPrueba.addAction(self.actionReload_configuration)
        self.menuPrueba.addAction(self.menuChange_language.menuAction())
        self.menuPrueba.addAction(self.actionSalir)
        self.menuHelp.addAction(self.actionAbout_mtvcgui)
        self.menubar.addAction(self.menuPrueba.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.runButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_mencoder)
        QtCore.QObject.connect(self.previewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.preview_command)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.stop_button_pressed)
        QtCore.QObject.connect(self.actionSave_configuration, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.save_configuration)
        QtCore.QObject.connect(self.actionAbout_mtvcgui, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.show_about_dialog)
        QtCore.QObject.connect(self.showAudioCodecsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.show_available_audio_codecs)
        QtCore.QObject.connect(self.showVideoCodecsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.show_available_video_codecs)
        QtCore.QObject.connect(self.number_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frequency.hide)
        QtCore.QObject.connect(self.number_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.channel.show)
        QtCore.QObject.connect(self.freq_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.channel.hide)
        QtCore.QObject.connect(self.freq_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frequency.show)
        QtCore.QObject.connect(self.scheduleButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.shedule_recording)
        QtCore.QObject.connect(self.cancel_sheduleButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cancel_shedule)
        QtCore.QObject.connect(self.actionReload_configuration, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.set_params_from_config)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.preview_with_mplayer)
        QtCore.QObject.connect(self.audiocodec, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.audio_codec_selected)
        QtCore.QObject.connect(self.videocodec, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.video_codec_selected)
        QtCore.QObject.connect(self.channel, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.channel_changed)
        QtCore.QObject.connect(self.frequency, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.frequency_changed)
        QtCore.QObject.connect(self.brightnessSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.brightness_changed)
        QtCore.QObject.connect(self.contrastSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.contrast_changed)
        QtCore.QObject.connect(self.hueSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.hue_changed)
        QtCore.QObject.connect(self.saturationSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.saturation_changed)
        QtCore.QObject.connect(self.device, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.update_device_values)
        QtCore.QObject.connect(self.actionEnglish, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.changeToEnglish)
        QtCore.QObject.connect(self.actionSpanish, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.changeToSpanish)
        QtCore.QObject.connect(self.actionSpanish_Argentina, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.changeToSpanish_Argentina)
        QtCore.QObject.connect(self.actionItalian, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.changeToItalian)
        QtCore.QObject.connect(self.xvid_cbr, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.set_xvid_cbr)
        QtCore.QObject.connect(self.x264_cbr, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.set_x264_cbr)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mencoder TV Capture GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("MainWindow", "Preview command", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Norm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Channels list", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audio_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lavc audio options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Audio Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "Extra options (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.number_rb.setText(QtGui.QApplication.translate("MainWindow", "number", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_rb.setText(QtGui.QApplication.translate("MainWindow", "frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview channel with mplayer", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_video_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lavc video options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Video Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Extra options (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.lame_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lame options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Audio Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.extra_lame_opts_label.setText(QtGui.QApplication.translate("MainWindow", "Extra options (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.norm.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The tool will try to get the supported norms from mplayer based on current value of &quot;Device&quot;. However if this fails you may still enter any value for the norm, either by the norm name or its integer value norm or normid.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The tool will try to get the supported inputs from mplayer based on current value of &quot;Device&quot;. However if this fails you may still enter its integer value</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "x264 options", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_bitrate.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">bitrate=&lt;value&gt;</span></p><p>Sets the average bitrate to be used in kbits/second (default: off). Since local bitrate may vary, this average may be inaccurate for very short videos (see ratetol). Constant bitrate can be achieved by combining this with vbv_maxrate, at significant reduction in quality.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_bitrate_label.setText(QtGui.QApplication.translate("MainWindow", "bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_qp_label.setText(QtGui.QApplication.translate("MainWindow", "qp", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_qp.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">qp=&lt;0−51&gt;</span></p><p>This selects the quantizer to use for P-frames. I- and B-frames are offset from this value by ip_factor and pb_factor, respectively. 20−40 is a useful range (default: 26). Lower values result in better fidelity, but higher bitrates. 0 is lossless. Note that quantization in H.264 works differently from MPEG-1/2/4: H.264’s quantization parameter (QP) is on a logarithmic scale. The mapping is approximately H264QP = 12 + 6*log2(MPEGQP). For example, MPEG at QP=2 is equivalent to H.264 at QP=18.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Extra options (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_cbr.setText(QtGui.QApplication.translate("MainWindow", "CBR", None, QtGui.QApplication.UnicodeUTF8))
        self.x264_crf_label.setText(QtGui.QApplication.translate("MainWindow", "crf", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "xvid options", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_bitrate_label.setText(QtGui.QApplication.translate("MainWindow", "bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_fixed_quant_label.setText(QtGui.QApplication.translate("MainWindow", "fixed_quant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "me_quality", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_bitrate.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">bitrate=&lt;value&gt; (CBR or two pass mode)</span></p><p>Sets the bitrate to be used in kbits/second if &lt;16000 or in bits/second if &gt;16000. If &lt;value&gt; is negative, XviD will use its absolute value as the target size (in kBytes) of the video and compute the associated bitrate automagically (default: 687 kbits/s).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_fixed_quant.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">fixed_quant=&lt;1−31&gt;</span></p><p>Switch to fixed quantizer mode and specify the quantizer to be used.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_me_quality.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">me_quality=&lt;0−6&gt;</span></p><p>This option controls the motion estimation subsystem. The higher the value, the more precise the estimation should be (default: 6). The more precise the motion estimation is, the more bits can be saved. Precision is gained at the expense of CPU time so decrease this setting if you need realtime encoding.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_interlacing.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">interlacing</span></p><p>Encode the fields of interlaced video material. Turn this option on for interlaced content. </p><p>NOTE: Should you rescale the video, you would need an interlace-aware resizer, which you can activate with −vf scale=&lt;width&gt;:&lt;height&gt;:1</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_interlacing.setText(QtGui.QApplication.translate("MainWindow", "interlacing", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_cartoon.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">cartoon</span></p><p>Activate this if your encoded sequence is an anime/cartoon. It modifies some XviD internal thresholds so XviD takes better decisions on frame types and motion vectors for flat looking cartoons.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_cartoon.setText(QtGui.QApplication.translate("MainWindow", "cartoon", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Extra options (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.xvid_cbr.setText(QtGui.QApplication.translate("MainWindow", "CBR", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Main Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Extra tv parameters (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Audio Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.alsa_audio.setText(QtGui.QApplication.translate("MainWindow", "Capture audio using ALSA", None, QtGui.QApplication.UnicodeUTF8))
        self.adevice.setToolTip(QtGui.QApplication.translate("MainWindow", "You may find the available devices running the command\n"
"aplay --list-devices\n"
"on the console", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "ALSA device (e.g. hw.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Brightness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Extra TV Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Extra mencoder parameters (delimited by spaces)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.noskip.setText(QtGui.QApplication.translate("MainWindow", "noskip", None, QtGui.QApplication.UnicodeUTF8))
        self.quiet.setText(QtGui.QApplication.translate("MainWindow", "quiet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "FPS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Extra filters (delimited by ,)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Extra Mencoder Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Run this command before capturing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Run this command after capturing:", None, QtGui.QApplication.UnicodeUTF8))
        self.scheduleButton.setText(QtGui.QApplication.translate("MainWindow", "Schedule Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_sheduleButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.play_while_recording.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>It is absolutely not recommended to use this! It may consume too much CPU and ruin your capture!! It makes use of the \'tail\' command, so it must be available.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.play_while_recording.setText(QtGui.QApplication.translate("MainWindow", "Play recorded file while capture (kind of preview) (NOT RECOMMENDED)", None, QtGui.QApplication.UnicodeUTF8))
        self.setenvvars.setText(QtGui.QApplication.translate("MainWindow", "Set these environment variables:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.append_suffix.setText(QtGui.QApplication.translate("MainWindow", "Append a number suffix if file exists", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("MainWindow", "Stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPrueba.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuChange_language.setTitle(QtGui.QApplication.translate("MainWindow", "Change language", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_configuration.setText(QtGui.QApplication.translate("MainWindow", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_mtvcgui.setText(QtGui.QApplication.translate("MainWindow", "About mtvcgui", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_configuration.setText(QtGui.QApplication.translate("MainWindow", "Restore saved configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnglish.setText(QtGui.QApplication.translate("MainWindow", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpanish.setText(QtGui.QApplication.translate("MainWindow", "Spanish", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpanish_Argentina.setText(QtGui.QApplication.translate("MainWindow", "Spanish (Argentina)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionItalian.setText(QtGui.QApplication.translate("MainWindow", "Italian", None, QtGui.QApplication.UnicodeUTF8))

