# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mtvcgui.ui'
#
# Created: Fri Jun  8 03:19:17 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(694, 523)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.runButton = QtGui.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(190, 450, 95, 25))
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.outputfile = QtGui.QLineEdit(self.centralwidget)
        self.outputfile.setGeometry(QtCore.QRect(115, 360, 571, 26))
        self.outputfile.setObjectName(_fromUtf8("outputfile"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 365, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.previewButton = QtGui.QPushButton(self.centralwidget)
        self.previewButton.setGeometry(QtCore.QRect(535, 415, 151, 25))
        self.previewButton.setObjectName(_fromUtf8("previewButton"))
        self.previewcommand = QtGui.QLineEdit(self.centralwidget)
        self.previewcommand.setGeometry(QtCore.QRect(10, 415, 521, 26))
        self.previewcommand.setReadOnly(False)
        self.previewcommand.setObjectName(_fromUtf8("previewcommand"))
        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        self.stopButton.setGeometry(QtCore.QRect(380, 450, 95, 25))
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 10, 681, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(20, 135, 66, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 54, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.driver = QtGui.QComboBox(self.tab)
        self.driver.setGeometry(QtCore.QRect(90, 95, 121, 26))
        self.driver.setEditable(True)
        self.driver.setObjectName(_fromUtf8("driver"))
        self.driver.addItem(_fromUtf8(""))
        self.driver.addItem(_fromUtf8(""))
        self.device = QtGui.QLineEdit(self.tab)
        self.device.setGeometry(QtCore.QRect(90, 125, 121, 26))
        self.device.setObjectName(_fromUtf8("device"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(320, 20, 111, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.videocodec = QtGui.QComboBox(self.tab)
        self.videocodec.setGeometry(QtCore.QRect(440, 45, 201, 26))
        self.videocodec.setEditable(True)
        self.videocodec.setObjectName(_fromUtf8("videocodec"))
        self.videocodec.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 45, 54, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.chanlist = QtGui.QComboBox(self.tab)
        self.chanlist.setGeometry(QtCore.QRect(90, 215, 121, 26))
        self.chanlist.setEditable(True)
        self.chanlist.setObjectName(_fromUtf8("chanlist"))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.addItem(_fromUtf8(""))
        self.chanlist.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 220, 54, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.channel = QtGui.QSpinBox(self.tab)
        self.channel.setGeometry(QtCore.QRect(90, 35, 58, 26))
        self.channel.setObjectName(_fromUtf8("channel"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 105, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 75, 66, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(320, 50, 111, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.audiocodec = QtGui.QComboBox(self.tab)
        self.audiocodec.setGeometry(QtCore.QRect(440, 15, 201, 26))
        self.audiocodec.setEditable(True)
        self.audiocodec.setObjectName(_fromUtf8("audiocodec"))
        self.audiocodec.addItem(_fromUtf8(""))
        self.duration = QtGui.QTimeEdit(self.tab)
        self.duration.setGeometry(QtCore.QRect(90, 65, 118, 26))
        self.duration.setObjectName(_fromUtf8("duration"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lavc_audio_options_box = QtGui.QGroupBox(self.tab)
        self.lavc_audio_options_box.setGeometry(QtCore.QRect(325, 80, 341, 91))
        self.lavc_audio_options_box.setObjectName(_fromUtf8("lavc_audio_options_box"))
        self.lavc_audiobitrate = QtGui.QLineEdit(self.lavc_audio_options_box)
        self.lavc_audiobitrate.setGeometry(QtCore.QRect(175, 60, 113, 26))
        self.lavc_audiobitrate.setObjectName(_fromUtf8("lavc_audiobitrate"))
        self.label_19 = QtGui.QLabel(self.lavc_audio_options_box)
        self.label_19.setGeometry(QtCore.QRect(35, 40, 136, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.lavc_audio_options_box)
        self.label_20.setGeometry(QtCore.QRect(35, 70, 136, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lavc_audiocodec = QtGui.QComboBox(self.lavc_audio_options_box)
        self.lavc_audiocodec.setGeometry(QtCore.QRect(175, 30, 111, 26))
        self.lavc_audiocodec.setEditable(True)
        self.lavc_audiocodec.setObjectName(_fromUtf8("lavc_audiocodec"))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.lavc_audiocodec.addItem(_fromUtf8(""))
        self.showAudioCodecsButton = QtGui.QToolButton(self.tab)
        self.showAudioCodecsButton.setGeometry(QtCore.QRect(645, 15, 27, 25))
        self.showAudioCodecsButton.setObjectName(_fromUtf8("showAudioCodecsButton"))
        self.showVideoCodecsButton = QtGui.QToolButton(self.tab)
        self.showVideoCodecsButton.setGeometry(QtCore.QRect(645, 45, 27, 25))
        self.showVideoCodecsButton.setObjectName(_fromUtf8("showVideoCodecsButton"))
        self.number_rb = QtGui.QRadioButton(self.tab)
        self.number_rb.setGeometry(QtCore.QRect(205, 15, 96, 25))
        self.number_rb.setChecked(True)
        self.number_rb.setObjectName(_fromUtf8("number_rb"))
        self.freq_rb = QtGui.QRadioButton(self.tab)
        self.freq_rb.setGeometry(QtCore.QRect(205, 40, 96, 25))
        self.freq_rb.setObjectName(_fromUtf8("freq_rb"))
        self.frequency = QtGui.QDoubleSpinBox(self.tab)
        self.frequency.setGeometry(QtCore.QRect(91, 35, 116, 26))
        self.frequency.setDecimals(3)
        self.frequency.setMaximum(9999.99)
        self.frequency.setObjectName(_fromUtf8("frequency"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 260, 211, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.lavc_video_options_box = QtGui.QGroupBox(self.tab)
        self.lavc_video_options_box.setGeometry(QtCore.QRect(325, 190, 341, 80))
        self.lavc_video_options_box.setObjectName(_fromUtf8("lavc_video_options_box"))
        self.label_22 = QtGui.QLabel(self.lavc_video_options_box)
        self.label_22.setGeometry(QtCore.QRect(35, 60, 136, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_21 = QtGui.QLabel(self.lavc_video_options_box)
        self.label_21.setGeometry(QtCore.QRect(35, 30, 136, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lavc_videobitrate = QtGui.QLineEdit(self.lavc_video_options_box)
        self.lavc_videobitrate.setGeometry(QtCore.QRect(175, 55, 151, 26))
        self.lavc_videobitrate.setObjectName(_fromUtf8("lavc_videobitrate"))
        self.lavc_videocodec = QtGui.QComboBox(self.lavc_video_options_box)
        self.lavc_videocodec.setGeometry(QtCore.QRect(175, 25, 151, 26))
        self.lavc_videocodec.setEditable(True)
        self.lavc_videocodec.setObjectName(_fromUtf8("lavc_videocodec"))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lavc_videocodec.addItem(_fromUtf8(""))
        self.lame_options_box = QtGui.QGroupBox(self.tab)
        self.lame_options_box.setGeometry(QtCore.QRect(325, 80, 346, 80))
        self.lame_options_box.setObjectName(_fromUtf8("lame_options_box"))
        self.label_28 = QtGui.QLabel(self.lame_options_box)
        self.label_28.setGeometry(QtCore.QRect(35, 30, 116, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lame_audiobitrate = QtGui.QLineEdit(self.lame_options_box)
        self.lame_audiobitrate.setGeometry(QtCore.QRect(185, 25, 113, 26))
        self.lame_audiobitrate.setObjectName(_fromUtf8("lame_audiobitrate"))
        self.norm = QtGui.QComboBox(self.tab)
        self.norm.setGeometry(QtCore.QRect(90, 155, 121, 26))
        self.norm.setEditable(True)
        self.norm.setObjectName(_fromUtf8("norm"))
        self.input = QtGui.QComboBox(self.tab)
        self.input.setGeometry(QtCore.QRect(90, 185, 121, 26))
        self.input.setEditable(True)
        self.input.setObjectName(_fromUtf8("input"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(40, 210, 521, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.extratvparms = QtGui.QLineEdit(self.tab_2)
        self.extratvparms.setGeometry(QtCore.QRect(32, 230, 541, 26))
        self.extratvparms.setObjectName(_fromUtf8("extratvparms"))
        self.tvwidth = QtGui.QLineEdit(self.tab_2)
        self.tvwidth.setGeometry(QtCore.QRect(110, 10, 113, 26))
        self.tvwidth.setText(_fromUtf8(""))
        self.tvwidth.setObjectName(_fromUtf8("tvwidth"))
        self.tvheight = QtGui.QLineEdit(self.tab_2)
        self.tvheight.setGeometry(QtCore.QRect(110, 40, 113, 26))
        self.tvheight.setText(_fromUtf8(""))
        self.tvheight.setObjectName(_fromUtf8("tvheight"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(10, 45, 96, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.audiorate = QtGui.QLineEdit(self.tab_2)
        self.audiorate.setGeometry(QtCore.QRect(110, 70, 113, 26))
        self.audiorate.setText(_fromUtf8(""))
        self.audiorate.setObjectName(_fromUtf8("audiorate"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 75, 81, 46))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(230, 75, 54, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.alsa_audio = QtGui.QCheckBox(self.tab_2)
        self.alsa_audio.setGeometry(QtCore.QRect(10, 125, 321, 23))
        self.alsa_audio.setObjectName(_fromUtf8("alsa_audio"))
        self.adevice = QtGui.QLineEdit(self.tab_2)
        self.adevice.setGeometry(QtCore.QRect(10, 155, 131, 26))
        self.adevice.setObjectName(_fromUtf8("adevice"))
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(150, 160, 216, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.brightnessSlider = QtGui.QSlider(self.tab_2)
        self.brightnessSlider.setGeometry(QtCore.QRect(490, 15, 160, 23))
        self.brightnessSlider.setMinimum(-100)
        self.brightnessSlider.setMaximum(100)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.brightnessSlider.setObjectName(_fromUtf8("brightnessSlider"))
        self.contrastSlider = QtGui.QSlider(self.tab_2)
        self.contrastSlider.setGeometry(QtCore.QRect(490, 45, 160, 23))
        self.contrastSlider.setMinimum(-100)
        self.contrastSlider.setMaximum(100)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.contrastSlider.setObjectName(_fromUtf8("contrastSlider"))
        self.hueSlider = QtGui.QSlider(self.tab_2)
        self.hueSlider.setGeometry(QtCore.QRect(490, 75, 160, 23))
        self.hueSlider.setMinimum(-100)
        self.hueSlider.setMaximum(100)
        self.hueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hueSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.hueSlider.setObjectName(_fromUtf8("hueSlider"))
        self.saturationSlider = QtGui.QSlider(self.tab_2)
        self.saturationSlider.setGeometry(QtCore.QRect(490, 105, 160, 23))
        self.saturationSlider.setMinimum(-100)
        self.saturationSlider.setMaximum(100)
        self.saturationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturationSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.saturationSlider.setObjectName(_fromUtf8("saturationSlider"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(385, 15, 86, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(385, 45, 101, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(385, 75, 101, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setGeometry(QtCore.QRect(385, 105, 101, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(40, 220, 451, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.extramencoderparms = QtGui.QLineEdit(self.tab_3)
        self.extramencoderparms.setGeometry(QtCore.QRect(32, 240, 541, 26))
        self.extramencoderparms.setText(_fromUtf8(""))
        self.extramencoderparms.setObjectName(_fromUtf8("extramencoderparms"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 66, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 45, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.scalewidth = QtGui.QLineEdit(self.tab_3)
        self.scalewidth.setGeometry(QtCore.QRect(90, 10, 113, 26))
        self.scalewidth.setText(_fromUtf8(""))
        self.scalewidth.setObjectName(_fromUtf8("scalewidth"))
        self.scaleheight = QtGui.QLineEdit(self.tab_3)
        self.scaleheight.setGeometry(QtCore.QRect(90, 40, 113, 26))
        self.scaleheight.setText(_fromUtf8(""))
        self.scaleheight.setObjectName(_fromUtf8("scaleheight"))
        self.noskip = QtGui.QCheckBox(self.tab_3)
        self.noskip.setGeometry(QtCore.QRect(420, 20, 84, 23))
        self.noskip.setObjectName(_fromUtf8("noskip"))
        self.quiet = QtGui.QCheckBox(self.tab_3)
        self.quiet.setGeometry(QtCore.QRect(420, 50, 84, 23))
        self.quiet.setChecked(True)
        self.quiet.setObjectName(_fromUtf8("quiet"))
        self.ofps = QtGui.QLineEdit(self.tab_3)
        self.ofps.setGeometry(QtCore.QRect(90, 70, 113, 26))
        self.ofps.setText(_fromUtf8(""))
        self.ofps.setObjectName(_fromUtf8("ofps"))
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(20, 75, 61, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.extrafilters = QtGui.QLineEdit(self.tab_3)
        self.extrafilters.setGeometry(QtCore.QRect(30, 180, 541, 26))
        self.extrafilters.setText(_fromUtf8(""))
        self.extrafilters.setObjectName(_fromUtf8("extrafilters"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(40, 160, 456, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(20, 15, 621, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(20, 85, 616, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.pre_command = QtGui.QLineEdit(self.tab_4)
        self.pre_command.setGeometry(QtCore.QRect(15, 30, 626, 26))
        self.pre_command.setObjectName(_fromUtf8("pre_command"))
        self.post_command = QtGui.QLineEdit(self.tab_4)
        self.post_command.setGeometry(QtCore.QRect(15, 105, 626, 26))
        self.post_command.setObjectName(_fromUtf8("post_command"))
        self.recording_date = QtGui.QDateTimeEdit(self.tab_4)
        self.recording_date.setGeometry(QtCore.QRect(15, 270, 194, 26))
        self.recording_date.setObjectName(_fromUtf8("recording_date"))
        self.scheduleButton = QtGui.QPushButton(self.tab_4)
        self.scheduleButton.setGeometry(QtCore.QRect(225, 270, 186, 25))
        self.scheduleButton.setObjectName(_fromUtf8("scheduleButton"))
        self.cancel_sheduleButton = QtGui.QPushButton(self.tab_4)
        self.cancel_sheduleButton.setEnabled(False)
        self.cancel_sheduleButton.setGeometry(QtCore.QRect(440, 270, 186, 25))
        self.cancel_sheduleButton.setCheckable(False)
        self.cancel_sheduleButton.setObjectName(_fromUtf8("cancel_sheduleButton"))
        self.play_while_recording = QtGui.QCheckBox(self.tab_4)
        self.play_while_recording.setGeometry(QtCore.QRect(20, 145, 611, 23))
        self.play_while_recording.setObjectName(_fromUtf8("play_while_recording"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.append_suffix = QtGui.QCheckBox(self.centralwidget)
        self.append_suffix.setGeometry(QtCore.QRect(10, 385, 666, 23))
        self.append_suffix.setChecked(True)
        self.append_suffix.setObjectName(_fromUtf8("append_suffix"))
        self.status_label = QtGui.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(495, 455, 186, 16))
        self.status_label.setObjectName(_fromUtf8("status_label"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPrueba = QtGui.QMenu(self.menubar)
        self.menuPrueba.setObjectName(_fromUtf8("menuPrueba"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionSave_configuration = QtGui.QAction(MainWindow)
        self.actionSave_configuration.setObjectName(_fromUtf8("actionSave_configuration"))
        self.actionAbout_mtvcgui = QtGui.QAction(MainWindow)
        self.actionAbout_mtvcgui.setObjectName(_fromUtf8("actionAbout_mtvcgui"))
        self.actionReload_configuration = QtGui.QAction(MainWindow)
        self.actionReload_configuration.setObjectName(_fromUtf8("actionReload_configuration"))
        self.menuPrueba.addAction(self.actionSave_configuration)
        self.menuPrueba.addAction(self.actionReload_configuration)
        self.menuPrueba.addAction(self.actionSalir)
        self.menuHelp.addAction(self.actionAbout_mtvcgui)
        self.menubar.addAction(self.menuPrueba.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.runButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.run_mencoder)
        QtCore.QObject.connect(self.previewButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.preview_command)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.stop_button_pressed)
        QtCore.QObject.connect(self.actionSave_configuration, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.save_configuration)
        QtCore.QObject.connect(self.actionAbout_mtvcgui, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.show_about_dialog)
        QtCore.QObject.connect(self.showAudioCodecsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.show_available_audio_codecs)
        QtCore.QObject.connect(self.showVideoCodecsButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.show_available_video_codecs)
        QtCore.QObject.connect(self.number_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frequency.hide)
        QtCore.QObject.connect(self.number_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.channel.show)
        QtCore.QObject.connect(self.freq_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.channel.hide)
        QtCore.QObject.connect(self.freq_rb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frequency.show)
        QtCore.QObject.connect(self.scheduleButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.shedule_recording)
        QtCore.QObject.connect(self.cancel_sheduleButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.cancel_shedule)
        QtCore.QObject.connect(self.actionReload_configuration, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.set_params_from_config)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.preview_with_mplayer)
        QtCore.QObject.connect(self.audiocodec, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.audio_codec_selected)
        QtCore.QObject.connect(self.videocodec, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.video_codec_selected)
        QtCore.QObject.connect(self.channel, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.channel_changed)
        QtCore.QObject.connect(self.frequency, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.frequency_changed)
        QtCore.QObject.connect(self.brightnessSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.brightness_changed)
        QtCore.QObject.connect(self.contrastSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.contrast_changed)
        QtCore.QObject.connect(self.hueSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.hue_changed)
        QtCore.QObject.connect(self.saturationSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), MainWindow.saturation_changed)
        QtCore.QObject.connect(self.device, QtCore.SIGNAL(_fromUtf8("editingFinished()")), MainWindow.update_device_values)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "mencoder TV Capture GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.runButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.outputfile.setText(QtGui.QApplication.translate("MainWindow", "./capture_{%channel_%Y%m%d_%H%M%S}.avi", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.previewButton.setText(QtGui.QApplication.translate("MainWindow", "preview command", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "norm", None, QtGui.QApplication.UnicodeUTF8))
        self.driver.setItemText(0, QtGui.QApplication.translate("MainWindow", "v4l2", None, QtGui.QApplication.UnicodeUTF8))
        self.driver.setItemText(1, QtGui.QApplication.translate("MainWindow", "v4l", None, QtGui.QApplication.UnicodeUTF8))
        self.device.setText(QtGui.QApplication.translate("MainWindow", "/dev/video0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.videocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "null", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(0, QtGui.QApplication.translate("MainWindow", "us-cable", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(1, QtGui.QApplication.translate("MainWindow", "us-bcast", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(2, QtGui.QApplication.translate("MainWindow", "europe-east", None, QtGui.QApplication.UnicodeUTF8))
        self.chanlist.setItemText(3, QtGui.QApplication.translate("MainWindow", "europe-west", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "chanlist", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Driver", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Duration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.audiocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "null", None, QtGui.QApplication.UnicodeUTF8))
        self.duration.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "HH:mm:ss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audio_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lavc audio options", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiobitrate.setText(QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Audio Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Audio Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "mp2", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiocodec.setItemText(1, QtGui.QApplication.translate("MainWindow", "ac3", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiocodec.setItemText(2, QtGui.QApplication.translate("MainWindow", "adpcm_ima_wav", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_audiocodec.setItemText(3, QtGui.QApplication.translate("MainWindow", "mp3", None, QtGui.QApplication.UnicodeUTF8))
        self.showAudioCodecsButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.showVideoCodecsButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.number_rb.setText(QtGui.QApplication.translate("MainWindow", "number", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_rb.setText(QtGui.QApplication.translate("MainWindow", "frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Preview channel with mplayer", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_video_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lavc video options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Video Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Video Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videobitrate.setText(QtGui.QApplication.translate("MainWindow", "3000", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(0, QtGui.QApplication.translate("MainWindow", "mpeg4", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(1, QtGui.QApplication.translate("MainWindow", "mjpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(2, QtGui.QApplication.translate("MainWindow", "h263", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(3, QtGui.QApplication.translate("MainWindow", "h263p", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(4, QtGui.QApplication.translate("MainWindow", "mspeg4", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(5, QtGui.QApplication.translate("MainWindow", "mspeg4v2", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(6, QtGui.QApplication.translate("MainWindow", "wmv1", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(7, QtGui.QApplication.translate("MainWindow", "wmv2", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(8, QtGui.QApplication.translate("MainWindow", "rv10", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(9, QtGui.QApplication.translate("MainWindow", "mpeg1video", None, QtGui.QApplication.UnicodeUTF8))
        self.lavc_videocodec.setItemText(10, QtGui.QApplication.translate("MainWindow", "huffyuv", None, QtGui.QApplication.UnicodeUTF8))
        self.lame_options_box.setTitle(QtGui.QApplication.translate("MainWindow", "lame options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Audio Bitrate", None, QtGui.QApplication.UnicodeUTF8))
        self.lame_audiobitrate.setText(QtGui.QApplication.translate("MainWindow", "128", None, QtGui.QApplication.UnicodeUTF8))
        self.norm.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The tool will try to get the supported norms from mplayer based on current value of &quot;Device&quot;. However if this fails you may still enter any value for the norm, either by the norm name or its integer value norm or normid.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.input.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>The tool will try to get the supported inputs from mplayer based on current value of &quot;Device&quot;. However if this fails you may still enter its integer value</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Main Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Extra tv parameters (delimited by :)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Audio Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.alsa_audio.setText(QtGui.QApplication.translate("MainWindow", "Capture audio using ALSA", None, QtGui.QApplication.UnicodeUTF8))
        self.adevice.setToolTip(QtGui.QApplication.translate("MainWindow", "You may find the available devices running the command\n"
"aplay --list-devices\n"
"on the console", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "ALSA device (e.g. hw.0)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Brightness", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Contrast", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Hue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Saturation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Extra TV Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Extra mencoder parameters (delimited by spaces)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.noskip.setText(QtGui.QApplication.translate("MainWindow", "noskip", None, QtGui.QApplication.UnicodeUTF8))
        self.quiet.setText(QtGui.QApplication.translate("MainWindow", "quiet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "FPS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Extra filters (delimited by ,)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Extra Mencoder Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Run this command before capturing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Run this command after capturing:", None, QtGui.QApplication.UnicodeUTF8))
        self.scheduleButton.setText(QtGui.QApplication.translate("MainWindow", "Schedule Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_sheduleButton.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.play_while_recording.setText(QtGui.QApplication.translate("MainWindow", "Play recorded file while capture (kind of preview) (May consume too much cpu and ruin your capture!!)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.append_suffix.setText(QtGui.QApplication.translate("MainWindow", "Append a number suffix if file exists", None, QtGui.QApplication.UnicodeUTF8))
        self.status_label.setText(QtGui.QApplication.translate("MainWindow", "Stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPrueba.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_configuration.setText(QtGui.QApplication.translate("MainWindow", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_mtvcgui.setText(QtGui.QApplication.translate("MainWindow", "About mtvcgui", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_configuration.setText(QtGui.QApplication.translate("MainWindow", "Restore saved configuration", None, QtGui.QApplication.UnicodeUTF8))

